3_rails/proyectos/config/routes.rb
Proyectos::Application.routes.draw do
  
  devise_for :users

  root :to => 'projects#index'
  
  resources :projects
  
end

3_rails/proyectos/app/models/project.rb
class Project < ActiveRecord::Base
  
end

3_rails/proyectos/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  
end

3_rails/proyectos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

3_rails/proyectos/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :authenticate_user!, 
                :only => [:create, :edit, :new, :update, :destroy]
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    @project.save
    redirect_to @project
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def index
    @projects = Project.all
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    @project.update_attributes(params[:project])
    redirect_to @project
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
  
end

3_rails/proyectos/app/helpers/application_helper.rb
module ApplicationHelper
end

3_rails/proyectos/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

3_rails/proyectos/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

3_rails/proyectos/app/helpers/projects_helper.rb
module ProjectsHelper
end

3_rails/proyectos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

3_rails/proyectos/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <p>
    <%= f.label :name, 'Nombre' %><br />
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :description, 'Descripción' %><br />
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :start, 'Inicio del proyecto' %><br />
    <%= f.date_select :start %>
  </p>
  
  <p>
    <%= f.submit 'Crear proyecto' %>
  </p>
  
<% end %>

3_rails/proyectos/app/views/projects/edit.html.erb
<h1>Editar proyecto</h1>

<%= render :partial => 'form' %>

3_rails/proyectos/app/views/projects/index.html.erb
<h1>Proyectos</h1>

<%= link_to "Nuevo proyecto", new_project_path %>
<br /><br />
<table>
  <% @projects.each do |project| %>
    <tr>
      
      <td>
        <strong><%= link_to project.name, project %></strong>
      <td>
      <td>
        <%= truncate project.description, :size => 10 %>
      </td>
      <td>
        <%= project.start %>
      </td>
      <td>
        <%= link_to "Editar", edit_project_path(project) %>
      </td>
      <td>
        <%= link_to "Eliminar", project, 
                    :method => :delete, 
                    :confirm => 'Estas seguro de que quieres eliminar el proyecto?' %>
      </td>
    </tr>
  <% end %>
</table>

3_rails/proyectos/app/views/projects/new.html.erb
<h1>Crear un nuevo proyecto</h1>

<%= render :partial => 'form' %>

3_rails/proyectos/app/views/projects/show.html.erb
<h1>
  <%= @project.name %>
</h1>

<p>
  <%= @project.description %>
</p>